export const AudioEvents = {
    PLAY_SOUND: "PLAY_SOUND",
    SOUND_STOP: "SOUND_STOP",
    PLAY_BACKGROUND_SOUND: "PLAY_BACKGROUND_SOUND",
    STOP_BACKGROUND_SOUND: "STOP_BACKGROUND_SOUND",
    FADE_IN_SOUND: "FADE_IN_SOUND",
    FADE_OUT_SOUND: "FADE_OUT_SOUND",
    MUTE_AUDIO: "MUTE_AUDIO",
    UNMUTE_AUDIO: "UNMUTE_AUDIO",
    MUTE_AUDIO_CHECK: "MUTE_AUDIO_CHECK",
    UNMUTE_AUDIO_CHECK: "UNMUTE_AUDIO_CHECK",
    STOP_CURRENT_SOUND: "STOP_CURRENT_SOUND"
}