export const GameEvents = {

    // intents
    INTENT_START_REEL_SPIN: "INTENT_START_REEL_SPIN",
    INTENT_STOP_REEL_SPIN: "INTENT_STOP_REEL_SPIN",

    UPDATE_GAME_STATE: "UPDATE_GAME_STATE",
    INITIALIZE_GAME_REQUEST : "INITIALIZE_GAME_REQUEST",
    INITIALIZE_GAME_RESPONSE : "INITIALIZE_GAME_RESPONSE",
    SHOW_BASEGAME : "SHOW_BASEGAME",
    SHOW_BONUSGAME: "SHOW_BONUSGAME",
    SHOW_REELS: "SHOW_REELS",
    END_LOADING_SCREEN: "END_LOADING_SCREEN",
    LOADING_SCREEN_ASSETS_LOADED: "LOADING_SCREEN_ASSETS_LOADED",
    ASSETS_LOADED: "ASSETS_LOADED",
    START_REEL_SPIN: "START_REEL_SPIN",
    REEL_SPIN_STARTED: "REEL_SPIN_STARTED",
    GAME_RESPONSE_RECIEVED: "GAME_RESPONSE_RECIEVED",
    STOP_REEL_SPIN: "STOP_REEL_SPIN",
    MANUAL_STOP_REEL_SPIN: "MANUAL_STOP_REEL_SPIN",
    MANUAL_STOP: "MANUAL_STOP",
    ENABLE_PLAY_BTN_AFTER_SPIN: "ENABLE_PLAY_BTN_AFTER_SPIN",
    REELS_SPIN_STOPPED: "REELS_SPIN_STOPPED",
    CLEAR_SYMBOL_ANIMATIONS: "CLEAR_SYMBOL_ANIMATIONS",
    ISVISIBLE_BOTTOM_RIBBON: "ISVISIBLE_BOTTOM_RIBBON",
    TOGGLE_WINS: "TOGGLE_WINS",
    SET_WIN_AMOUNT: "SET_WIN_AMOUNT",
    UPDATE_BALANCE: "UPDATE_BALANCE",
    REMOVE_SYMBOLS_DURING_BONUS: "REMOVE_SYMBOLS_DURING_BONUS",
    RESTORE_NORMAL_SYMBOLS_AFTER_BONUS: "RESTORE_NORMAL_SYMBOLS_AFTER_BONUS",

    GAME_BET_RESULT_REQUEST: "GAME_BET_RESULT_REQUEST",
    GAME_BET_RESULT_RESPONSE: "GAME_BET_RESULT_RESPONSE",
    OPEN_PLAY_REQUEST: "OPEN_PLAY_REQUEST",
    OPEN_PLAY_RESPONSE: "OPEN_PLAY_RESPONSE",
    PLACE_BET_REQUEST: "PLACE_BET_REQUEST",
    PLACE_BET_RESPONSE: "PLACE_BET_RESPONSE",
    SETTLE_PLAY_REQUEST: "SETTLE_PLAY_REQUEST",
    SETTLE_PLAY_RESPONSE: "SETTLE_PLAY_RESPONSE",
    GET_JACKPOTS_REQUEST: "GET_JACKPOTS_REQUEST",
    CLOSE_PLAY_REQUEST: "CLOSE_PLAY_REQUEST",

    // leander API events
    LENDER_API_INITIALIZED :"LENDER_API_INITIALIZED",
    LEANDER_API_OPEN_PLAY : "LEANDER_API_OPEN_PLAY",
    LEANDER_API_SETTLE_PLAY : "LEANDER_API_SETTLE_PLAY",
    LEANDER_API_CLOSE_PLAY : "LEANDER_API_CLOSE_PLAY",
    LEANDER_API_IDLE_PLAY : "LEANDER_API_IDLE_PLAY",
    PRE_LOADING: "PRE_LOADING",
    BALANCE_UPDATED_GAME:"BALANCE_UPDATED_GAME",
    TOTAL_BET_UPDATED:"TOTAL_BET_UPDATED",
    TOTAL_WIN_UPDATED:"TOTAL_WIN_UPDATED",
    PLAY_ID_UPDATED:"PLAY_ID_UPDATED",

    // Autoplay 
    AUTOPLAY_ROUND: "AUTOPLAY_ROUND",
    BET_AMOUNT_CHANGED: "BET_AMOUNT_CHANGED",
    AUTOPLAY_PLAY: "AUTOPLAY_PLAY",
    AUTOPLAY_STOP: "AUTOPLAY_STOP",
    AUTOPLAY_DEFAULT: "AUTOPLAY_DEFAULT",

    //freeSpin
    UPDATE_FREE_SPIN_REEL_STRIPS: "UPDATE_FREE_SPIN_REEL_STRIPS",
    UPDATE_JACKPOT_REEL_STRIPS: "UPDATE_JACKPOT_REEL_STRIPS",
    UPDATE_REEL_STRIPS : "UPDATE_REEL_STRIPS",
    FREE_SPIN: "FREE_SPIN",
    FREE_SPIN_ACTIVATED:"FREE_SPIN_ACTIVATED",
    FREE_SPIN_SAVE_DATA: "FREE_SPIN_SAVE_DATA",
    FREE_SPIN_SETTLE_DATA: "FREE_SPIN_SETTLE_DATA",
    FREE_SPIN_UPDATE_BG: "FREE_SPIN_UPDATE_BG",

    // big win
    SHOW_BIG_WIN: "SHOW_BIG_WIN",
    // Broken game
    BROKEN_GAME_FREE_SPIN_RESPONSE_RECEIVED: "BROKEN_GAME_FREE_SPIN_RESPONSE_RECEIVED",
    
    // Enable Disable
    PLAY_START: "PLAY_START",
    PLAY_STOP: "PLAY_STOP",
    MENU_ENABLE: "MENU_ENABLE",
    MENU_DISABLE: "MENU_DISABLE",
    DECREASE_BET_ENABLE: "DECREASE_BET_ENABLE",
    DECREASE_BET_DISABLE: "DECREASE_BET_DISABLE",
    INCREASE_BET_ENABLE: "INCREASE_BET_ENABLE",
    INCREASE_BET_DISABLE: "INCREASE_BET_DISABLE",
    MAX_BET_ENABLE: "MAX_BET_ENABLE",
    MAX_BET_DISABLE: "MAX_BET_DISABLE",
    PLAY_ENABLE: "PLAY_ENABLE",
    PLAY_DISABLE: "PLAY_DISABLE",
    PAUSE_ENABLE: "PAUSE_ENABLE",
    PAUSE_DISABLE: "PAUSE_DISABLE",
    AUTO_PLAY_ENABLE: "AUTO_PLAY_ENABLE",
    AUTO_PLAY_DISABLE: "AUTO_PLAY_DISABLE",
    SOUND_ENABLE: "SOUND_ENABLE",
    SOUND_DISABLE: "SOUND_DISABLE",
    TOGGLE_TURBO: "TOGGLE_TURBO",

    // bonus info
    BONUS_BASE_LOCK_INFO: "BONUS_BASE_LOCK_INFO",
    START_WHEEL_ROUND: "START_WHEEL_ROUND",
    END_WHEEL_ROUND: "END_WHEEL_ROUND"
}